//
// Created by zhouj on 2022/12/12.
//

#ifndef WWMOTOR_LIBS_WWBASE_PERIPHERAL_TEMPLATE_PERIPHERAL_CONFIG_HPP_
#define WWMOTOR_LIBS_WWBASE_PERIPHERAL_TEMPLATE_PERIPHERAL_CONFIG_HPP_

#define PERIPHERAL_I2C_WRITE_IT_ENABLED   1
#define PERIPHERAL_I2C_WRITE_DMA_ENABLED  0
#define PERIPHERAL_I2C_READ_IT_ENABLED    1
#define PERIPHERAL_I2C_READ_DMA_ENABLED   0
#define PERIPHERAL_SPI_WRITE_IT_ENABLED   1
#define PERIPHERAL_SPI_WRITE_DMA_ENABLED  0
#define PERIPHERAL_SPI_READ_IT_ENABLED    1
#define PERIPHERAL_SPI_READ_DMA_ENABLED   0
#define PERIPHERAL_UART_WRITE_IT_ENABLED  1
#define PERIPHERAL_UART_WRITE_DMA_ENABLED 0
#define PERIPHERAL_UART_READ_IT_ENABLED   1
#define PERIPHERAL_UART_READ_DMA_ENABLED  0

#endif  // WWMOTOR_LIBS_WWBASE_PERIPHERAL_TEMPLATE_PERIPHERAL_CONFIG_HPP_
